#!groovy
import org.folio.Constants
import org.folio.jenkins.JenkinsAgentLabel
import org.folio.jenkins.PodTemplates
import org.folio.models.TerraformConfig

@Library('pipelines-shared-library@RANCHER-650-Jenkins-upgrade') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '20')),
  disableConcurrentBuilds(),
  parameters([
    folioParameters.cluster(),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

TerraformConfig tfConfig = new TerraformConfig('terraform/rancher/cluster')
  .withWorkspace(params.CLUSTER)

ansiColor('xterm') {
  PodTemplates podTemplates = new PodTemplates(this)

  podTemplates.defaultTemplate {
    node(JenkinsAgentLabel.DEFAULT_AGENT.getLabel()) {
      stage('Ini') {
        buildName "#${params.CLUSTER}.${env.BUILD_ID}"
      }

      stage('Checkout') {
        git(url: "${Constants.FOLIO_GITHUB_URL}/pipelines-shared-library.git",
          branch: folioTools.getPipelineBranch(),
          credentialsId: Constants.PRIVATE_GITHUB_CREDENTIALS_ID,
          poll: false)
      }

      folioTerraformFlow.manageCluster('destroy', tfConfig)
    }
  }
}
