#!groovy
import org.folio.models.TerraformConfig

@Library('pipelines-shared-library@RANCHER-1390') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '20')),
  disableConcurrentBuilds(),
  parameters([
    folioParameters.cluster(),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

TerraformConfig tfConfig = new TerraformConfig('terraform/rancher/cluster')
  .withWorkspace(params.CLUSTER)

ansiColor('xterm') {
  folioTerraformFlow.manageCluster('destroy', tfConfig)
}
