#!groovy
import groovy.transform.Field
import org.folio.Constants
import org.folio.jenkins.JenkinsAgentLabel
import org.folio.jenkins.PodTemplates
import org.folio.models.parameters.CreateNamespaceParameters
import org.folio.rest_v2.PlatformType
import org.jenkinsci.plugins.workflow.libs.Library

//TODO remove branch before merge to master
@Library('pipelines-shared-library@RANCHER-2236') _

@Field final String deleteNamespaceJobName = Constants.JENKINS_DELETE_NAMESPACE_JOB
@Field final String createNamespaceJobName = Constants.JENKINS_CREATE_NAMESPACE_FROM_BRANCH_JOB

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([folioParameters.platform(),
              folioParameters.cluster('PLATFORM'),
              folioParameters.namespace(),
              folioParameters.configType(),
              folioParameters.refreshParameters()]),
  pipelineTriggers([
    parameterizedCron('''
      H 20 * * * %PLATFORM=EUREKA;CLUSTER=folio-edev;NAMESPACE=eureka;CONFIG_TYPE=development;AGENT=jenkins-agent-java21
    ''')])
])
// Get back when the ticket is resolved https://folio-org.atlassian.net/browse/RANCHER-1546
//            pipelineTriggers([parameterizedCron('''
//              H 20 * * * %CLUSTER=folio-edev;NAMESPACE=eureka;EUREKA=true;CONFIG_TYPE=development;AGENT=rancher
//            ''')])])


if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

PodTemplates podTemplates = new PodTemplates(this)

CreateNamespaceParameters namespace = new CreateNamespaceParameters.Builder()
  .platform(PlatformType.EUREKA)
  .clusterName(params.CLUSTER)
  .namespaceName(params.NAMESPACE)
  .folioBranch('snapshot')
  .okapiVersion('latest')
  .configType(params.CONFIG_TYPE)
  .loadReference(true)
  .loadSample(true)
  .consortia(true)
  .linkedData(true)
  .rwSplit(false)
  .greenmail(false)
  .mockServer(false)
  .rtr(false)
  .splitFiles(true)
  .ecsCCL(false)
  .applicationSet('Complete')
  .applications(org.folio.rest_v2.Constants.APPLICATION_BRANCH('Complete'))
  .hasSecureTenant(true)
  .secureTenantId(folioDefault.consortiaTenants().get('university').getTenantId())
  .dataset(false)
  .pgType('built-in')
  .pgVersion('16.1')
  .kafkaType('built-in')
  .opensearchType('aws')
  .s3Type('built-in')
  .uiBuild(true)
  .runSanityCheck(true)
  .build()

ansiColor('xterm') {
  podTemplates.defaultTemplate {
    node(JenkinsAgentLabel.DEFAULT_AGENT.getLabel()) {
      stage('Checkout') {
        checkout scm
      }

      stage('Build name') {
        buildName "${namespace.getClusterName()}-${namespace.getNamespaceName()}.${env.BUILD_ID}"
        buildDescription "Config: development"
      }

      stage('Cleaning env') {
        folioTriggerJob.deleteNamespace(deleteNamespaceJobName, namespace)
      }

      stage('Spinning up env') {
        folioTriggerJob.createNamespaceFromBranch(createNamespaceJobName, namespace)
      }
    }
  }
}
