#!groovy
import org.folio.Constants
import org.folio.jenkins.PodTemplates
import org.jenkinsci.plugins.workflow.libs.Library

@Library('pipelines-shared-library') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  pipelineTriggers([cron('0 22 * * 0')]),
  parameters([
    folioParameters.cluster(),
    folioParameters.namespace(),
    string(name: 'SSM_PATTERN_SUFFIX',
           defaultValue: '_test',
           description: '(Optional) SSM parameter name suffix to match for deletion. Defaults to "_test". Combined with cluster-namespace prefix: <CLUSTER>-<NAMESPACE><SUFFIX>'),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

if (params.CLUSTER == 'folio-testing' || params.CLUSTER == 'folio-etesting' ||
      params.CLUSTER == 'folio-perf' || params.CLUSTER == 'folio-eperf') {
  folioCommon.kitfoxApproval()
}

PodTemplates podTemplates = new PodTemplates(this)

String ssmPattern = "${params.CLUSTER}-${params.NAMESPACE}${params.SSM_PATTERN_SUFFIX}"

ansiColor('xterm') {
  podTemplates.rancherAgent {
    stage('Ini') {
      buildName("#${params.CLUSTER}-${params.NAMESPACE}.${env.BUILD_ID}")
      buildDescription("SSM pattern: ${ssmPattern}")
    }

    stage('Checkout') {
      checkout(poll: false,
        scm: scmGit(branches: [[name: "*/${folioTools.getPipelineBranch()}"]],
          extensions: [cloneOption(depth: 50, noTags: true, reference: '', shallow: true)],
          userRemoteConfigs: [[credentialsId: Constants.PRIVATE_GITHUB_CREDENTIALS_ID,
                               url          : "${Constants.FOLIO_GITHUB_URL}/pipelines-shared-library.git"]]))
    }

    stage('[AWS Parameter Store] Cleanup') {
      awscli.withAwsClient {
        folioTools.deleteSSMParametersByPattern(ssmPattern)
      }
    }
  }
}
