#!groovy
import org.folio.Constants
import org.folio.jenkins.PodTemplates
import org.jenkinsci.plugins.workflow.libs.Library

@Library('pipelines-shared-library@ssm-cleanup') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  pipelineTriggers([cron('0 22 * * 0')]),
  parameters([
    string(name: 'TENANT_PATTERNS',
           defaultValue: 'test,university,college,central',
           description: 'Comma-separated list of tenant ID prefixes to match for deletion. Applied per namespace as: folio-edev-<namespace>_<prefix>. Examples: "testtenant,university,college,central"'),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

PodTemplates podTemplates = new PodTemplates(this)

ansiColor('xterm') {
  podTemplates.rancherAgent {
    stage('Ini') {
      buildName("#${env.BUILD_ID}")
      buildDescription("Tenant patterns: ${params.TENANT_PATTERNS}")
    }

    stage('Checkout') {
      checkout(poll: false,
        scm: scmGit(branches: [[name: "*/${folioTools.getPipelineBranch()}"]],
          extensions: [cloneOption(depth: 50, noTags: true, reference: '', shallow: true)],
          userRemoteConfigs: [[credentialsId: Constants.PRIVATE_GITHUB_CREDENTIALS_ID,
                               url          : "${Constants.FOLIO_GITHUB_URL}/pipelines-shared-library.git"]]))
    }

    stage('[AWS Parameter Store] Cleanup') {
      awscli.withAwsClient {
        List tenantPrefixes = params.TENANT_PATTERNS.tokenize(',').collect { it.trim() }
        Constants.AWS_EKS_DEV_NAMESPACES.each { namespace ->
          folioTools.deleteTestTenantSSMParameters('folio-edev', namespace, tenantPrefixes)
        }
      }
    }
  }
}
