#!groovy
import org.folio.Constants
import org.folio.jenkins.PodTemplates
import org.jenkinsci.plugins.workflow.libs.Library

@Library('pipelines-shared-library') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  pipelineTriggers([cron('0 22 * * 0')]),
  parameters([
    string(name: 'SSM_PATTERN',
           defaultValue: '_test',
           description: 'SSM parameter name pattern to match for deletion (e.g. "_test" matches all parameters containing "_test")'),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

PodTemplates podTemplates = new PodTemplates(this)

ansiColor('xterm') {
  podTemplates.rancherAgent {
    stage('Ini') {
      buildName("#${env.BUILD_ID}")
      buildDescription("SSM pattern: ${params.SSM_PATTERN}")
    }

    stage('Checkout') {
      checkout(poll: false,
        scm: scmGit(branches: [[name: "*/${folioTools.getPipelineBranch()}"]],
          extensions: [cloneOption(depth: 50, noTags: true, reference: '', shallow: true)],
          userRemoteConfigs: [[credentialsId: Constants.PRIVATE_GITHUB_CREDENTIALS_ID,
                               url          : "${Constants.FOLIO_GITHUB_URL}/pipelines-shared-library.git"]]))
    }

    stage('[AWS Parameter Store] Cleanup') {
      awscli.withAwsClient {
        folioTools.deleteSSMParametersByPattern(params.SSM_PATTERN)
      }
    }
  }
}
