AWSTemplateFormatVersion: 2010-09-09
Resources:
  AWSCURDatabase:
    Type: "AWS::Glue::Database"
    Properties:
      DatabaseInput:
        Name: "athenacurcfn_aws_kubecost"
      CatalogId: !Ref AWS::AccountId

  AWSCURCrawlerComponentFunction:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSGlueServiceRole"
      Policies:
        - PolicyName: AWSCURCrawlerComponentFunction
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub "arn:${AWS::Partition}:logs:*:*:*"
              - Effect: Allow
                Action:
                  - "glue:UpdateDatabase"
                  - "glue:UpdatePartition"
                  - "glue:CreateTable"
                  - "glue:UpdateTable"
                  - "glue:ImportCatalogToGlue"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: !Sub "arn:${AWS::Partition}:s3:::aws-athena-query-results-kubecost-folio/reports/aws-kubecost/aws-kubecost*"
        - PolicyName: AWSCURKMSDecryption
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "kms:Decrypt"
                Resource: "*"

  AWSCURCrawlerLambdaExecutor:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: AWSCURCrawlerLambdaExecutor
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub "arn:${AWS::Partition}:logs:*:*:*"
              - Effect: Allow
                Action:
                  - "glue:StartCrawler"
                Resource: "*"

  AWSCURCrawler:
    Type: "AWS::Glue::Crawler"
    DependsOn:
      - AWSCURDatabase
      - AWSCURCrawlerComponentFunction
    Properties:
      Name: AWSCURCrawler-aws-kubecost
      Description: A recurring crawler that keeps your CUR table in Athena up-to-date.
      Role: !GetAtt AWSCURCrawlerComponentFunction.Arn
      DatabaseName: !Ref AWSCURDatabase
      Targets:
        S3Targets:
          - Path: "s3://aws-athena-query-results-kubecost-folio/reports/aws-kubecost/aws-kubecost"
            Exclusions:
              - "**.json"
              - "**.yml"
              - "**.sql"
              - "**.csv"
              - "**.gz"
              - "**.zip"
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DELETE_FROM_DATABASE

  AWSCURInitializer:
    Type: "AWS::Lambda::Function"
    DependsOn: AWSCURCrawler
    Properties:
      Code:
        ZipFile: >
          const { GlueClient, StartCrawlerCommand } = require('@aws-sdk/client-glue');
          const response = require('./cfn-response');
          exports.handler = async function(event, context, callback) {
            if (event.RequestType === 'Delete') {
              response.send(event, context, response.SUCCESS);
              return;
            }

            const glue = new GlueClient({});
            const command = new StartCrawlerCommand({ Name: 'AWSCURCrawler-aws-kubecost' });

            try {
              await glue.send(command);
              if (event.ResponseURL) {
                response.send(event, context, response.SUCCESS);
              } else {
                callback(null, response.SUCCESS);
              }
            } catch (err) {
              if (err.name === 'CrawlerRunningException') {
                callback(null, err.message);
              } else {
                const responseString = JSON.stringify(err);
                if (event.ResponseURL) {
                  response.send(event, context, response.FAILED, { msg: responseString });
                } else {
                  callback(responseString);
                }
              }
            }
          };
      Handler: "index.handler"
      Timeout: 30
      Runtime: nodejs20.x
      ReservedConcurrentExecutions: 1
      Role: !GetAtt AWSCURCrawlerLambdaExecutor.Arn

  AWSStartCURCrawler:
    Type: "Custom::AWSStartCURCrawler"
    Properties:
      ServiceToken: !GetAtt AWSCURInitializer.Arn

  AWSS3CUREventLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt AWSCURInitializer.Arn
      Principal: "s3.amazonaws.com"
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub "arn:${AWS::Partition}:s3:::aws-athena-query-results-kubecost-folio"

  AWSS3CURLambdaExecutor:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: AWSS3CURLambdaExecutor
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub "arn:${AWS::Partition}:logs:*:*:*"
              - Effect: Allow
                Action:
                  - "s3:PutBucketNotification"
                Resource: !Sub "arn:${AWS::Partition}:s3:::aws-athena-query-results-kubecost-folio"

  AWSS3CURNotification:
    Type: "AWS::Lambda::Function"
    DependsOn:
      - AWSCURInitializer
      - AWSS3CUREventLambdaPermission
      - AWSS3CURLambdaExecutor
    Properties:
      Code:
        ZipFile: >
          const { S3Client, PutBucketNotificationConfigurationCommand } = require('@aws-sdk/client-s3');
          const response = require('./cfn-response');
          exports.handler = async function(event, context, callback) {
            const s3 = new S3Client({});

            const newNotificationConfig = {};
            if (event.RequestType !== 'Delete') {
              newNotificationConfig.LambdaFunctionConfigurations = [{
                Events: [ 's3:ObjectCreated:*' ],
                LambdaFunctionArn: event.ResourceProperties.TargetLambdaArn || 'missing arn',
                Filter: { Key: { FilterRules: [ { Name: 'prefix', Value: event.ResourceProperties.ReportKey } ] } }
              }];
            }

            const command = new PutBucketNotificationConfigurationCommand({
              Bucket: event.ResourceProperties.BucketName,
              NotificationConfiguration: newNotificationConfig
            });

            try {
              const result = await s3.send(command);
              response.send(event, context, response.SUCCESS, result);
              callback(null, result);
            } catch (error) {
              response.send(event, context, response.FAILED, error);
              console.log(error);
              callback(error);
            }
          };
      Handler: "index.handler"
      Timeout: 30
      Runtime: nodejs20.x
      ReservedConcurrentExecutions: 1
      Role: !GetAtt AWSS3CURLambdaExecutor.Arn

  AWSPutS3CURNotification:
    Type: "Custom::AWSPutS3CURNotification"
    Properties:
      ServiceToken: !GetAtt AWSS3CURNotification.Arn
      TargetLambdaArn: !GetAtt AWSCURInitializer.Arn
      BucketName: "aws-athena-query-results-kubecost-folio"
      ReportKey: "reports/aws-kubecost/aws-kubecost"

  AWSCURReportStatusTable:
    Type: "AWS::Glue::Table"
    DependsOn: AWSCURDatabase
    Properties:
      DatabaseName: athenacurcfn_aws_kubecost
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: "cost_and_usage_data_status"
        TableType: "EXTERNAL_TABLE"
        StorageDescriptor:
          Columns:
            - Name: status
              Type: "string"
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
          Location: "s3://aws-athena-query-results-kubecost-folio/reports/aws-kubecost/cost_and_usage_data_status/"
