package v2.namespaces.update

import hudson.AbortException
import org.folio.Constants
import org.folio.models.EurekaNamespace
import org.folio.models.module.EurekaModule
import org.folio.models.parameters.ModuleBuildPushPipeline
import org.folio.rest_v2.PlatformType
import org.folio.rest_v2.eureka.Eureka
import org.folio.utilities.Logger
import org.jenkinsci.plugins.pipeline.modeldefinition.Utils
import org.jenkinsci.plugins.workflow.libs.Library
import org.jenkinsci.plugins.workflow.support.steps.build.RunWrapper

@Library('pipelines-shared-library@RANCHER-2057-test') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  parameters([
    folioParameters.platform(PlatformType.EUREKA),
    folioParameters.cluster('PLATFORM'),
    folioParameters.namespace(),
    booleanParam(name: 'UPDATE_ALL', defaultValue: true, description: 'Update all namespace modules with latest versions'),
    folioParameters.moduleName(PlatformType.EUREKA), // MODULE_NAME, Folio Module name
    folioParameters.moduleSource(), // MODULE_SOURCE, Eureka Module source (Github, DockerHub, AWS ECR)
    folioParameters.branchWithRef('MODULE_BRANCH', 'MODULE_NAME'), // MODULE_BRANCH, Eureka Module Github branch
    folioParameters.containerImageTag('CONTAINER_IMAGE_TAG', 'MODULE_NAME, MODULE_SOURCE'), // CONTAINER_IMAGE_TAG, Container image tag
    string(name: 'MAVEN_ARGS', defaultValue: '-DskipTests', description: 'Maven build arguments'),
    folioParameters.configType(),
    folioParameters.agent(Constants.JENKINS_AGENTS_BUILD_MODULE),
    folioParameters.refreshParameters()
    , folioParameters.hideParameters(
      [
        'GitHub/folio-org': ['CONTAINER_IMAGE_TAG'],
        'DockerHub/folioci': ['MODULE_BRANCH', 'MAVEN_ARGS'],
        'DockerHub/folioorg': ['MODULE_BRANCH', 'MAVEN_ARGS'],
        'ECR': ['MODULE_BRANCH', 'MAVEN_ARGS']
      ]
      , "MODULE_SOURCE"
    )
    , folioParameters.hideParameters(
      [
        'on': ['MODULE_NAME', 'MODULE_SOURCE', 'MODULE_BRANCH', 'CONTAINER_IMAGE_TAG', 'MAVEN_ARGS']
      ]
      , "UPDATE_ALL"
    )
    , folioParameters.hideParameters([ 'PLATFORM' ])
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

ansiColor('xterm') {
  node(params.AGENT) {

    Logger logger = new Logger(this, env.JOB_BASE_NAME)

    EurekaNamespace namespace = new EurekaNamespace(params.CLUSTER, params.NAMESPACE)
      .withDeploymentConfigType(params.CONFIG_TYPE) as EurekaNamespace

    namespace.addDeploymentConfig(folioTools.getPipelineBranch())

    boolean isEnvActive = false
    folioHelm.withKubeConfig(namespace.getClusterName()) {
      isEnvActive = sh(script: "kubectl get pods --namespace ${namespace.getNamespaceName()} --no-headers", returnStdout: true).trim()
    }

    if (!isEnvActive){
      logger.warning("Target environment is not running. Please start the environment and try again.")

      currentBuild.result = 'ABORTED'
      return
    }

    boolean updateAll = params.UPDATE_ALL
    String source = params.MODULE_SOURCE
    boolean isGithub = source.contains('GitHub')

    String moduleName = params.MODULE_NAME
    String branch = params.MODULE_BRANCH
    String args = params.MAVEN_ARGS.trim()

    Eureka eureka = new Eureka(this, namespace.generateDomain('kong'), namespace.generateDomain('keycloak'))
    List<EurekaModule> modules = []

    try {
      stage('Init') {
        buildName "#${params.MODULE_NAME}.${env.BUILD_ID}"
        buildDescription """Env: ${namespace.getWorkspaceName()}
${updateAll ? "Full update" : "Source: " + source }"""
      }

      stage('[GitHub] Build & Push Module') {
        if (!isGithub) {
          logger.info("Skip [Maven/Gradle] Build artifact stage")
          Utils.markStageSkippedForConditional('[GitHub] Build & Push Module')
        } else {

          RunWrapper buildResult = new ModuleBuildPushPipeline(this)
            .withModuleName(moduleName)
            .withModuleBranch(branch)
            .withMavenArgs(args)
            .doPushImage(true)
            .doPushDescriptor(true)
            .withAgent(params.AGENT)
            .run()

          if (!buildResult.rawBuild.getArtifacts().any { it.getFileName() == 'execution_results.json' })
            error "No execution_results.json artifact found"

          copyArtifacts(
            projectName: ModuleBuildPushPipeline.JOB_NAME,
            selector: specific(buildResult.getNumber().toString()),
            filter: 'execution_results.json'
          )

          logger.info("moduleId: ${readJSON(file: 'execution_results.json').moduleId}")

          modules.add(new EurekaModule().loadModuleDetails(readJSON(file: 'execution_results.json').moduleId as String))

          input message: "Let's wait"
        }
      }

      stage('[DockerHub/ECR] Module init') {
        if (isGithub || updateAll) {
          logger.info("Skip [DockerHub/ECR] Module init stage")
          Utils.markStageSkippedForConditional('[DockerHub/ECR] Module init')
        } else {

          EurekaModule module = new EurekaModule().loadModuleDetails("${moduleName}-${params.CONTAINER_IMAGE_TAG}")

          // Load Module Descriptor from Folio Descriptor Registry
          String getModuleDescriptorFromRegistry = "curl -s ${org.folio.rest_v2.Constants.OKAPI_REGISTRY}/_/proxy/modules/${module.name}-${module.version}"
          String moduleDescriptor = sh(label: "Get Module Descriptor from Folio Descriptor Registry", returnStdout: true, script: getModuleDescriptorFromRegistry).trim()

          logger.debug("Module Descriptor URL: ${getModuleDescriptorFromRegistry}")
          logger.debug("Module Descriptor: ${moduleDescriptor}")

          module.descriptor = [readJSON(text: moduleDescriptor)]

          // Upload Module Descriptor to Eureka Descriptor Registry
          sh(label: "Put Module Descriptor to Eureka Descriptor Registry",
            returnStdout: false,
            script: "curl -sS -X PUT ${Constants.EUREKA_REGISTRY_URL}${module.name}-${module.version} --data @- <<EOF\n${moduleDescriptor}\nEOF"
          )

          modules.add(module)
        }
      }

      stage('Env scanning') {
        eureka.getExistedTenantsFlow().values()
                .each {namespace.addTenant(it)}

        logger.debug("Configured Tenants: ${namespace.tenants}")
        logger.debug("Configured Tenants: ${namespace.modules.installJsonObject}")

        input message: "Let's wait"
      }

      stage('[REST] Get Tenants with Module') {
        deployAppModule.getTenantsWithModule(logger, eureka, module, namespace)
      }

      stage("Retrieve module's sidecar"){
        folioHelm.withKubeConfig(namespace.getClusterName()) {
          String sidecarImage =
            kubectl.getDeploymentContainerImageName(namespace.getNamespaceName(), module.getName(), "sidecar")
              .replace(':', '-')

          // In case updated module doesn't have Sidecar let's seek for it in other modules.
          if(!sidecarImage) {
            EurekaModule moduleWithSidecar = namespace.modules.getInstallJsonObject().find { fetchedModule ->
              kubectl.getDeploymentContainerImageName(namespace.getNamespaceName(), fetchedModule.getName(), "sidecar")
                      .replace(':', '-')
            }

            sidecarImage =
              kubectl.getDeploymentContainerImageName(namespace.getNamespaceName(), moduleWithSidecar.getName(), "sidecar")
                      .replace(':', '-')
          }

          if(sidecarImage)
            namespace.modules.addModule(sidecarImage)
          else
            throw new AbortException('There are no modules with sidecar in the namespace')
        }

        logger.debug("Configured Tenants: ${namespace.tenants}")
        logger.debug("Configured Applications: ${namespace.applications}")
        logger.debug("Namespace modules: ${namespace.modules.installJsonObject}")
      }

      stage('Update Module Version') {
        deployAppModule.updateModuleVersionFlow(logger, eureka, module, namespace)
      }

    } catch (e) {
      logger.warning("Caught exception: ${e}")
      error(e.getMessage())
    } finally {
      stage('Cleanup') {
        logger.debug("Workspace size: ${sh(returnStdout: true, script: 'du -sh .').trim()}")
        cleanWs notFailBuild: true
      }
    }
  }
}
