#!groovy
package folioRancher.folioDevTools.moduleDeployment.setEnvVarForDeployment

import org.folio.Constants
import org.folio.jenkins.PodTemplates
import org.folio.utilities.Logger
import org.jenkinsci.plugins.workflow.libs.Library

@Library('pipelines-shared-library@RANCHER-2996') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
          folioParameters.cluster(),
          folioParameters.namespace(),
          folioParameters.moduleName(),
          string(name: 'ENV_VAR_NAME', defaultValue: '', description: 'Environment variable name to set for the deployment'),
          string(name: 'ENV_VAR_VALUE', defaultValue: '', description: 'Environment variable value to set for the deployment'),
          booleanParam(name: 'SET_ENV_VAR_SIDECAR', defaultValue: false, description: 'Set environment variable for sidecar container too'),
          folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

PodTemplates podTemplates = new PodTemplates(this)
Logger logger = new Logger(this, env.JOB_BASE_NAME)

ansiColor('xterm') {
  podTemplates.rancherAgent {
    stage('Ini') {
      buildName "${params.CLUSTER}-${params.NAMESPACE}"
      buildDescription "${params.MODULE_NAME}: ${params.ENV_VAR_NAME}=${params.ENV_VAR_VALUE}"
    }

    stage('Checkout') {
      checkout scm
    }

    stage('[Set Env Var]') {
      folioHelm.withKubeConfig(params.CLUSTER) {
          logger.info("Setting env var for ${params.MODULE_NAME} deployment")
          def containers = params.SET_ENV_VAR_SIDECAR ? "--containers=*" : ""
          sh(script: "kubectl set env deployment/${params.MODULE_NAME} ${params.ENV_VAR_NAME.trim()}=${params.ENV_VAR_VALUE.trim()} --namespace ${params.NAMESPACE} ${containers}".trim(), returnStdout: true)
      }
    }
  }
}
