#!groovy
package folioRancher.folioEureka.DockerImages

import org.folio.eureka.EurekaImage
import org.jenkinsci.plugins.workflow.libs.Library

@Library('pipelines-shared-library@RANCHER-1334') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
    folioParameters.eurekaModules(),
    string(name: 'BRANCH', defaultValue: 'master', description: '(Optional) Branch or tag to build from'),
    folioParameters.agent(),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

ansiColor('xterm') {
  node(params.AGENT) {
    try {
      stage('Build Docker Image'){
        dir("${params.MODULE_NAME}"){
          EurekaImage image = new EurekaImage(this)
          image.setModuleName("${params.MODULE_NAME}")
          image.makeImage()
        }
      }
    } catch (e) {
      println("Caught exception: ${e}")
      error(e.getMessage())
    } finally {
      stage('Cleanup') {
        println("Workspace size: ${sh(returnStdout: true, script: 'du -sh .').trim()}")
        cleanWs notFailBuild: true
      }
    }
  }
}
