#!groovy
import groovy.transform.Field
import jenkins.model.Jenkins
import org.folio.jenkins.PodTemplates
import org.folio.models.OkapiTenant
import org.folio.models.OkapiUser
import org.folio.models.RancherNamespace
import org.folio.models.parameters.CreateNamespaceParameters
import org.folio.models.parameters.CypressTestsParameters
import org.folio.utilities.Logger
import org.jenkinsci.plugins.workflow.libs.Library

@Library('pipelines-shared-library') _

properties([
  pipelineTriggers([cron('H 0 * * 2-6')]),
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
    string(name: 'CYPRESS_BRANCH', defaultValue: 'master', description: "(Required) Insert what 'stripes-testing' branch use for build"),
    string(name: 'NUMBER_WORKERS', defaultValue: '4', description: "(Required) Define number of workers for Cypress tests execution"),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

PodTemplates podTemplates = new PodTemplates(this)
Logger logger = new Logger(this, env.JOB_BASE_NAME)

CreateNamespaceParameters namespaceBaseParams = new CreateNamespaceParameters.Builder()
  .clusterName('folio-etesting')
  .namespaceName('cypress')
  .kafkaType('aws')
  .build(this)

RancherNamespace namespace = new RancherNamespace(namespaceBaseParams.getClusterName(), namespaceBaseParams.getNamespaceName())

CypressTestsParameters cypressParameters = new CypressTestsParameters()
cypressParameters.setCiBuildId(env.JOB_BASE_NAME)
cypressParameters.setTestsSrcBranch(params.CYPRESS_BRANCH)
cypressParameters.setTenantUrl("https://${namespace.generateDomain('consortium')}")
cypressParameters.setOkapiUrl("https://${namespace.getDomains().kong}")
cypressParameters.setTenant(new OkapiTenant('consortium')
  .withAdminUser(new OkapiUser('consortium_admin', 'admin')))
cypressParameters.setCompileExecParameters('tags="smokeECS criticalPathECS extendedPathECS" env=ecs_env_name="snapshot",eureka=true,ecsEnabled=true')
cypressParameters.setNumberOfWorkers(params.NUMBER_WORKERS.toInteger())
cypressParameters.setTimeout('1080')

boolean reportPortalUse = true
String reportPortalRunType = 'evrk'

@Field final String mainPipelineJobName = 'folioScheduledTesting/runNightlyCypressEurekaTests'

ansiColor('xterm') {
  podTemplates.rancherAgent {
    stage('Ini') {
      buildDescription "Branch: ${params.CYPRESS_BRANCH}\nEnv: ${cypressParameters.tenantUrl}"
    }

    stage('[Wait] Main pipeline completion') {
      timeout(time: 4, unit: 'HOURS') {
        waitUntil(initialRecurrencePeriod: 60000, quiet: true) {
          boolean isRunning = Jenkins.instance.getItemByFullName(mainPipelineJobName)?.isBuilding() ?: false
          if (isRunning) {
            logger.info("'${mainPipelineJobName}' is still running. Waiting...")
          }
          return !isRunning
        }
      }
    }

    folioCypressFlow.call(cypressParameters.getCiBuildId(), [cypressParameters], true, reportPortalUse, reportPortalRunType, true)
  }
}
