edge-rtac:
  permissions:
  - rtac.all
edge-oai-pmh:
  tenants:
  - tenant: testoaipmh
    username: test-user
    password: test
  permissions:
  - oai-pmh.all
  - user-tenants.collection.get
edge-patron:
  permissions:
  - patron.all
  - users.collection.get
edge-orders:
  tenants:
  - tenant: testedgeorders
    username: test-user
    password: test
  permissions:
  - gobi.all
  - ebsconet.all
edge-ncip:
  permissions:
  - ncip.all
edge-dematic:
  tenants:
  - tenant: default
    username: stagingDirector
    firstName: stagingDirector
    lastName: SYSTEM
    password: default
    create: true
  permissions:
  - remote-storage.all
edge-caiasoft:
  tenants:
  - tenant: default
    username: caiaSoftClient
    firstName: caiaSoftClient
    lastName: SYSTEM
    password: default
    create: true
  permissions:
  - remote-storage.all
edge-inn-reach:
  tenants:
  - tenant: default
    username: innreachClient
    firstName: innreachClient
    lastName: SYSTEM
    password: default
    create: true
  permissions:
  - inn-reach.all
edge-connexion:
  permissions:
  - copycat.all
edge-sip2: {}
edge-courses: {}
edge-fqm: {}
edge-dcb: {}
