#!groovy
package folioRancher.folioNamespaceTools.manageNamespace.deploySecondRelease

import org.folio.Constants
import org.folio.far.Far
import org.folio.jenkins.PodTemplates
import org.folio.models.*
import org.folio.models.application.ApplicationList
import org.folio.models.module.FolioModule
import org.folio.models.parameters.InitializeFromScratchParameters
import org.folio.rest_v2.EntitlementApproach
import org.folio.rest_v2.eureka.Eureka
import org.folio.rest_v2.eureka.kong.Edge
import org.folio.utilities.Logger
import org.jenkinsci.plugins.workflow.libs.Library

import static groovy.json.JsonOutput.prettyPrint
import static groovy.json.JsonOutput.toJson

@Library('pipelines-shared-library@RANCHER-2967') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  parameters([
    folioParameters.cluster(),
    folioParameters.namespace(),
    folioParameters.platformBranch(),
    folioParameters.applicationsFromPlatform(),
    folioParameters.loadReference(),
    folioParameters.loadSample(),
    booleanParam(name: 'BUILD_UI', defaultValue: true, description: '(Optional) Set true to build and deploy UI bundles for diku2 and consortium2'),
    booleanParam(name: 'SC_NATIVE', defaultValue: true, description: '(Optional) Set false to use Java based SC image'),
    choice(name: 'ENTITLEMENT_APPROACH', choices: ['STATE', 'CREATE'], description: '(Optional) Entitlement method: STATE = PUT /entitlements/state (declarative), CREATE = POST /entitlements (procedural)'),
    booleanParam(name: 'SET_BASE_URL', defaultValue: true, description: '(Optional) Set false to skip PUT /base-url during tenant configuration'),
    folioParameters.configType(),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

ansiColor('xterm') {
  PodTemplates podTemplates = new PodTemplates(this, true)
  Logger logger = new Logger(this, 'deploySecondRelease')

  podTemplates.rancherJavaAgent() {
    try {
      stage('Init') {
        folioCommon.updateBuildName("#${params.CLUSTER}-${params.NAMESPACE}.${env.BUILD_ID}")
        folioCommon.updateBuildDescription("Branch: ${params.PLATFORM_BRANCH}\nConfig: ${params.CONFIG_TYPE}")
      }

      stage('Checkout') {
        checkout(scmGit(
          branches: [[name: "*/${folioTools.getPipelineBranch()}"]],
          extensions: [cloneOption(depth: 10, noTags: true, reference: '', shallow: true)],
          userRemoteConfigs: [[credentialsId: Constants.PRIVATE_GITHUB_CREDENTIALS_ID,
                               url          : "${Constants.FOLIO_GITHUB_URL}/pipelines-shared-library.git"]]))
      }

      Map platformDescriptor = folioDefault.getPlatformDescriptor(params.PLATFORM_BRANCH)
      List<Map<String, String>> allPlatformApps = folioDefault.getAllPlatformApps(params.PLATFORM_BRANCH, platformDescriptor)

      List<String> appIds = (params.APPLICATIONS as String)?.split(',')?.collect { it.trim() }?.findAll { it }?.collect { appName ->
        Map<String, String> appEntry = allPlatformApps.find { it.name == appName } as Map<String, String>
        if (!appEntry) {
          throw new Exception("Application '${appName}' not found in platform-descriptor.json")
        }
        appEntry.name + "-" + appEntry.version
      } ?: []

      Far far = new Far(this)
      ApplicationList apps = far.getApplicationsByIds(appIds)
      FolioInstallJson appModules = apps.getInstallJson()

      platformDescriptor['eureka-components']?.each { component ->
        appModules.addModule("${component['name']}-${component['version']}", 'enable')
      }
      logger.info("Added ${platformDescriptor['eureka-components']?.size() ?: 0} eureka-components to installJson")

      if (params.SC_NATIVE) {
        String tag = (awscli.listEcrImages(Constants.AWS_REGION, 'folio-module-sidecar')).replaceAll('"', '')
        logger.info("SC image tag: ${tag.replace(",", "")}")
        appModules.removeModuleByName('folio-module-sidecar')
        appModules.addModule("folio-module-sidecar-${tag.replace(",", "")}", 'enable')
      }

      String kongVersion = appModules.getKongModule()?.getVersion()
      String keycloakVersion = appModules.getKeycloakModule()?.getVersion()
      logger.info("Using Kong version: ${kongVersion}, Keycloak version: ${keycloakVersion}")

      boolean isRelease = (params.CONFIG_TYPE == 'release')
      String commitHash = common.getLastCommitHash('platform-lsp', params.PLATFORM_BRANCH)

      apps.each { application ->
        application.modules.each { module ->
          if (module.discovery?.location) {
            String name = module.discovery.name as String
            String loc = module.discovery.location as String
            if (!loc.contains("${name}2")) {
              module.setDiscovery(module.discovery + [location: loc.replace("http://${name}", "http://${name}2")])
            }
          }
        }
      }
      logger.info("Applied '2' suffix to all module discovery locations for 2nd release")

      List<Map<String, String>> installJson = appModules.getInstallJson()

      writeJSON(file: 'used-install-release2.json', json: installJson, pretty: 4)
      archiveArtifacts 'used-install-release2.json'

      logger.info("2nd release install JSON:\n${prettyPrint(toJson(installJson))}")

      EurekaNamespace namespace = new EurekaNamespace(params.CLUSTER, params.NAMESPACE)
      namespace.withSuperTenantAdminUser()
        .withDefaultTenant('diku2')
        .withDeploymentConfigType(params.CONFIG_TYPE)
      namespace.addDeploymentConfig(folioTools.getPipelineBranch())

      namespace.getDeploymentConfig().each { modName, cfg ->
        if (cfg instanceof Map) {
          cfg['releaseSupport'] = true
        }
      }

      Eureka eureka = new Eureka(this, namespace.generateDomain('kong'), namespace.generateDomain('keycloak'))

      TenantUi tenantUi = new TenantUi("${namespace.getClusterName()}-${namespace.getNamespaceName()}",
        commitHash, params.PLATFORM_BRANCH)
      tenantUi.setKongDomain(namespace.getDomains()['kong'])
      tenantUi.setKeycloakDomain(namespace.getDomains()['keycloak'])

      EurekaRequestParams installRequestParams = new EurekaRequestParams()
        .withIgnoreErrors(true)
        .withAsync(true)
        .doLoadReference(params.LOAD_REFERENCE)
        .doLoadSample(params.LOAD_SAMPLE) as EurekaRequestParams

      EurekaRequestParams consortiaParams2 = installRequestParams.clone()

      namespace.setEnableConsortia(true, isRelease)

      namespace.addTenant(
        new EurekaTenant('diku2')
          .withTenantName('Datalogisk Institut 2')
          .withTenantDescription('Danish Library Technology Institute 2 (created via Jenkins)')
          .withAdminUser(folioDefault.adminOkapiUser('diku2_admin', 'admin'))
          .withInstallJson(installJson)
          .withIndex(new Index('instance', true, true))
          .withIndex(new Index('authority', true, false))
          .withIndex(new Index('location', true, false))
          .withInstallRequestParams(installRequestParams.clone())
          .withTenantUi(tenantUi.clone())
      )

      Map defaultConsortiaTenants2 = folioDefault.consortiaTenantsExtra([], consortiaParams2 as InstallRequestParams)

      DTO.convertMapTo(defaultConsortiaTenants2, EurekaTenantConsortia.class)
        .values()
        .each { tenant ->
          tenant.withInstallJson(installJson)

          if (tenant.getIsCentralConsortiaTenant()) {
            TenantUi centralTenantUi = tenantUi.clone()
            centralTenantUi.setIsConsortia(true)
            centralTenantUi.setIsConsortiaSingleUi(false)
            tenant.withTenantUi(centralTenantUi)
          }

          namespace.addTenant(tenant)
        }

      stage('[Rest] Preinstall') {
        int counter = 0
        retry(5) {
          sleep time: (counter == 0 ? 0 : 30), unit: 'SECONDS'
          counter++

          eureka.registerApplications(apps)

          namespace.getTenants().values().each { tenant ->
            tenant.assignApplications(apps)

            if (tenant.tenantUi) {
              if (!tenant.tenantUi.getIsConsortia()) {
                tenant.tenantUi.removeUIComponents.add(new FolioModule().loadModuleDetails('folio_consortia-settings-0.0.0'))
                logger.info("Removed 'folio_consortia-settings' module from tenant ${tenant.getTenantId()} because it's not a consortia tenant")
              }

              ApplicationList linkedDataApp = apps.byName('app-linked-data')
              if (linkedDataApp.size() == 0) {
                tenant.tenantUi.removeUIComponents.add(new FolioModule().loadModuleDetails('folio_ld-folio-wrapper-0.0.0'))
                logger.info("Removed 'folio_ld-folio-wrapper' module from tenant ${tenant.getTenantId()} because 'app-linked-data' is not included in the installation")
              }
            }

            tenant.enableFolioExtensions(this, [])
          }

          namespace.withApplications(apps)
          eureka.registerModulesFlow(namespace.applications.getInstallJson())
        }
      }

      stage('[Helm] Deploy modules (2nd release)') {
        folioHelm.withKubeConfig(namespace.getClusterName(), {
          logger.info(namespace.getModules().getBackendModules())
          folioHelm.deployFolioModulesParallel(namespace, namespace.getModules().getBackendModules())
          folioHelm.checkDeploymentsRunning(namespace.getNamespaceName(), namespace.getModules().getBackendModules())
        }, true)
      }

      stage('[Helm] Deploy edge (2nd release)') {
        folioHelm.withKubeConfig(namespace.getClusterName(), {
          folioEdge.renderEphemeralPropertiesEureka(namespace)
          namespace.getModules().getEdgeModules().each { module ->
            kubectl.createConfigMap("${module.name}-ephemeral-properties", namespace.getNamespaceName(), "./${module.name}-ephemeral-properties")
          }
          folioHelm.deployFolioModulesParallel(namespace, namespace.getModules().getEdgeModules())
          folioHelm.checkDeploymentsRunning(namespace.getNamespaceName(), namespace.getModules().getEdgeModules())
        }, true)
      }

      stage('[Rest] Initialize (2nd release)') {
        InitializeFromScratchParameters initParams = new InitializeFromScratchParameters()
          .withEntitlementApproach(EntitlementApproach.valueOf(params.ENTITLEMENT_APPROACH))
          .withSetBaseUrl(params.SET_BASE_URL)

        int counter = 0
        retry(15) {
          sleep time: (counter == 0 ? 0 : 1), unit: 'MINUTES'
          counter++

          eureka.initializeFromScratch(
            namespace.getTenants(),
            namespace.getClusterName(),
            namespace.getNamespaceName(),
            namespace.getEnableConsortia(),
            initParams
          )
        }
      }

      stage('[Rest] Configure edge (2nd release)') {
        retry(5) {
          new Edge(this, "${namespace.generateDomain('kong')}", "${namespace.generateDomain('keycloak')}").createEurekaUsers(namespace)
        }
      }

      if (params.BUILD_UI) {
        stage('Build and deploy UI (2nd release)') {
          Map branches = [:]
          namespace.getTenants().each { tenantId, tenant ->
            if (tenant.getTenantUi()) {
              branches[tenantId] = {
                boolean isEcsBff = tenant.getTenantUi().getIsConsortia()
                folioUI.buildAndDeploy(namespace, tenant, isEcsBff)
              }
            }
          }
          parallel branches
        }
      }

      stage('[Notify] 2nd release') {
        slackSend(color: 'good', message: "${params.CLUSTER}-${params.NAMESPACE} 2nd release successfully deployed\n" +
          "1. https://${namespace.generateDomain('diku2')}\n" +
          "2. https://${namespace.generateDomain('consortium2')}",
          channel: Constants.SLACK_CHANNEL)
      }

    } catch (Exception e) {
      currentBuild.description = e.getMessage()
      currentBuild.result = 'FAILURE'
      logger.error(e)
    }
  }
}
