#!groovy

@Library('pipelines-shared-library@RANCHER-840') _

import org.folio.models.OkapiTenant
import org.folio.models.RancherNamespace
import org.folio.rest_v2.Main
import org.folio.rest_v2.Users
import org.folio.models.OkapiUser
import org.jenkinsci.plugins.workflow.libs.Library

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
    folioParameters.cluster(),
    folioParameters.namespace(),
    folioParameters.tenantId(''),
    folioParameters.userId(''),
    string(name: 'USERNAME', defaultValue: '', description: "New user's username"),
    string(name: 'PASSWORD', defaultValue: '', description: "New user's password"),
    string(name: 'BARCODE', defaultValue: '', description: "New user's barcode"),
    string(name: 'PATRON_GROUP', defaultValue: '', description: "New user's patron group"),
    string(name: 'PERMISSIONS', defaultValue: '', description: "New user's permissions"),
    folioParameters.agent(),
    folioParameters.refreshParameters()])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  error('DRY RUN BUILD, PARAMETERS REFRESHED!')
}

RancherNamespace namespace = new RancherNamespace(params.CLUSTER, params.NAMESPACE)
  .withSuperTenantAdminUser()

Main main = new Main(this, namespace.getDomains()['okapi'], namespace.getSuperTenant())

OkapiTenant tenant = new OkapiTenant(params.TENANT_ID)
OkapiUser user = new OkapiUser(params.USERNAME, params.PASSWORD)
Users createUser = new Users(this, namespace.getDomains()['okapi'])

ansiColor('xterm') {
  node(params.AGENT) {
    try {
      stage('Ini') {
        buildName "${namespace.getClusterName()}-${namespace.getNamespaceName()}.${env.BUILD_ID}"
        buildDescription "Tenant: ${params.TENANT_ID}"
      }
      stage("Create New User") {
        createUser.createUser(tenant, user)
        println("New User Created")
      }
      stage("Set Permissions") {
        main.deleteTenant(tenant)
      }
    } catch (exception) {
      println(exception)
      error(exception.getMessage())
    } finally {
      stage('Cleanup') {
        cleanWs notFailBuild: true
      }
    }
  }
}
