#!groovy
import org.jenkinsci.plugins.workflow.libs.Library

//TODO remove branch before merge to master
@Library('pipelines-shared-library@RANCHER-1574') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '50')),
//  disableConcurrentBuilds(),
  parameters([
    folioParameters.cluster(),
    folioParameters.namespace(),
    folioParameters.branch(),
    folioParameters.agent(),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

ansiColor('xterm') {
  node(params.AGENT) {
    try {

      stage('Tests start...') {
//        def eureka = new Eureka(this, 'https://folio-eureka-scout-kong.ci.folio.org/', false)
//        eureka.registerApplicationDiscovery('app-platform-minimal-1.0.0-SNAPSHOT.142')
        //eureka.registerApplication('app-platform-minimal-1.0.0-SNAPSHOT.161')
        folioEurekaApp.applicationDescriptorFileGenerator('app-platform-complete')
      }

    } catch (e) {
      println "Caught exception: ${e}"
      error(e.getMessage())
    } finally {
      stage('Cleanup') {
        cleanWs notFailBuild: true
      }
    }
  }
}
