#!groovy
import org.folio.rest_v2.Eureka
import org.jenkinsci.plugins.workflow.libs.Library

//TODO remove branch before merge to master
@Library('pipelines-shared-library@RANCHER-1352') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '50')),
//  disableConcurrentBuilds(),
  parameters([
    folioParameters.cluster(),
    folioParameters.namespace(),
    folioParameters.branch(),
    folioParameters.agent(),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

ansiColor('xterm') {
  node(params.AGENT) {
    try {

      stage('Tests start...') {
        def eureka = new Eureka(this, 'https://folio-eureka-scout-kong.ci.folio.org/', new OkapiTenant(), false)
        eureka.registerApplication('app-platform-complete-1.0.0-SNAPSHOT.62')
      }

    } catch (e) {
      println "Caught exception: ${e}"
      error(e.getMessage())
    } finally {
      stage('Cleanup') {
        cleanWs notFailBuild: true
      }
    }
  }
}
