#!groovy
import org.folio.models.OkapiTenant
import org.folio.rest_v2.Eureka
import org.jenkinsci.plugins.workflow.libs.Library
import org.folio.models.parameters.CreateNamespaceParameters

//TODO remove branch before merge to master
@Library('pipelines-shared-library@RANCHER-1574') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '50')),
//  disableConcurrentBuilds(),
  parameters([
    folioParameters.cluster(),
    folioParameters.namespace(),
    folioParameters.branch(),
    folioParameters.agent(),
    folioParameters.refreshParameters(),
    folioParameters.applicationId()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

ansiColor('xterm') {
  node(params.AGENT) {
    try {

      stage('Testing application creation') {
        folioEurekaApp.generateApplicationDescriptorFile(applicationId)
      }

    } catch (e) {
      println "Caught exception: ${e}"
      error(e.getMessage())
    } finally {
      stage('Cleanup') {
        cleanWs notFailBuild: true
      }
    }
  }
}
