#!groovy
import org.folio.models.RancherNamespace
import org.folio.models.parameters.CreateNamespaceParameters
import org.folio.models.parameters.KarateTestsParameters
import org.folio.utilities.Logger

@Library('pipelines-shared-library') _

/**
 * Job properties and parameters
 */
properties([
//  pipelineTriggers([cron('H 3 * * *')]),
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
    string(name: 'TESTS_BRANCH', defaultValue: 'master', description: "(Required) Karate tests repository branch to checkout"),
    string(name: 'THREADS_COUNT', defaultValue: '4', description: "(Required) Number of parallel threads"),
    booleanParam(name: 'DESTROY_AFTER', defaultValue: true, description: '(Optional) Set to false to not destroy namespace after tests execution'),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

/**
 * Job variables
 */
Logger logger = new Logger(this, env.JOB_BASE_NAME)

final String createNamespaceJobName = '/folioRancher/folioNamespaceTools/createNamespaceFromBranch'
final String deleteNamespaceJobName = '/folioRancher/folioNamespaceTools/deleteNamespace'
String okapiVersion = folioTools.eval(folioStringScripts.getOkapiVersions(), ['FOLIO_BRANCH': 'snapshot'])[0]

CreateNamespaceParameters namespaceBaseParams = new CreateNamespaceParameters.Builder()
  .clusterName('folio-testing')
  .namespaceName('karate')
  .rwSplit(false)
  .greenmail(false)
  .mockServer(true)
  .pgType('built-in')
  .pgVersion('16.1')
  .kafkaType('built-in')
  .opensearchType('built-in')
  .s3Type('built-in')
  .runSanityCheck(false)
  .members('')
  .worker('rancher')
  .build()

CreateNamespaceParameters namespaceFromBranchParams = namespaceBaseParams.toBuilder()
  .folioBranch('snapshot')
  .okapiVersion(okapiVersion)
  .configType('testing')
  .loadReference(true)
  .loadSample(true)
  .consortia(true)
  .rtr(false)
  .build()

RancherNamespace namespace = new RancherNamespace(namespaceBaseParams.getClusterName(), namespaceBaseParams.getNamespaceName())
namespace.withSuperTenantAdminUser()

KarateTestsParameters karateTestsParams = new KarateTestsParameters()
karateTestsParams.okapiUrl = "https://${namespace.getDomains().okapi}"
karateTestsParams.edgeUrl = "https://${namespace.getDomains().edge}"
karateTestsParams.tenant = namespace.getSuperTenant().getTenantId()
karateTestsParams.prototypeTenant = 'consortium'
karateTestsParams.adminUserName = namespace.getSuperTenant().getAdminUser().getUsername()
karateTestsParams.adminPassword = namespace.getSuperTenant().getAdminUser().getPassword()
karateTestsParams.threadsCount = params.THREADS_COUNT
karateTestsParams.reportPortalProjectName = 'junit5-integration'
karateTestsParams.sendSlackNotification = true
karateTestsParams.syncWithJira = true
karateTestsParams.timeout = '2'

/**
 * Pipeline
 */
ansiColor('xterm') {
  node('jenkins-agent-java17') {
    try {
      stage('Ini') {
        buildDescription "Branch: ${params.TESTS_BRANCH}\nThreads: ${params.THREADS_COUNT}\nDestroy after: ${params.DESTROY_AFTER}"
        cleanWs()
      }

      stage('[Job] Destroy environment (before)') {
        def nsExists
        folioHelm.withKubeConfig(namespaceBaseParams.getClusterName()) {
          nsExists = kubectl.checkNamespaceExistence("${namespaceBaseParams.getNamespaceName()}")
        }
        if (nsExists) {
          folioTriggerJob.deleteNamespace(deleteNamespaceJobName, namespaceBaseParams)
        } else {
          logger.warning("${namespaceBaseParams.getNamespaceName()} namespace does not exists!")
        }
      }

      stage('[Job] Provision environment') {
        folioTriggerJob.createNamespaceFromBranch(createNamespaceJobName, namespaceFromBranchParams)
      }

      stage('[Flow] Execute tests') {
        folioKarateFlow(karateTestsParams)
      }

      if (params.DESTROY_AFTER) {
        stage('[Job] Destroy environment (after)') {
          folioTriggerJob.deleteNamespace(deleteNamespaceJobName, namespaceBaseParams)
        }
      }
    } catch (e) {
      logger.warning("Caught exception: ${e}")
      error(e.getMessage())
    } finally {
      stage('Cleanup') {
        logger.debug("Workspace size: ${sh(returnStdout: true, script: 'du -sh .').trim()}")
        cleanWs notFailBuild: true
      }
    }
  }
}
