#!groovy
import org.folio.jenkins.JenkinsAgentLabel
import org.folio.jenkins.PodTemplates
import java.time.LocalDateTime

@Library('pipelines-shared-library@RANCHER-650-Jenkins-upgrade') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  parameters([
    string(name: 'TEAM_NAME', defaultValue: '', description: '(REQUIRED) Coma separated list of GitHub teams who need an access to the namespace'),
    string(name: 'NAMESPACE', defaultValue: '', description: '(REQUIRED) Possible values: folijet, spitfire, volaris etc.'),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

PodTemplates podTemplates = new PodTemplates(this)

ansiColor('xterm') {
  podTemplates.defaultTemplate {
    node(JenkinsAgentLabel.DEFAULT_AGENT.getLabel()) {
      stage('Ini') {
        buildName "Add GitHub team ${params.TEAM_NAME} to ${params.NAMESPACE}"
        buildDescription "${LocalDateTime.now().toString()}"
      }

      stage('Checkout') {
        checkout scm
      }

      stage('Add GitHub team') {
        folioTools.addGithubTeamsToRancherProjectMembersList("${params.TEAM_NAME}", "${params.NAMESPACE}")
      }
    }
  }
}
