#!groovy
import org.folio.models.OkapiTenant
import org.folio.models.OkapiUser
import org.folio.models.parameters.CypressTestsParameters
import org.jenkinsci.plugins.workflow.libs.Library

@Library('pipelines-shared-library') _

properties([
  //pipelineTriggers([cron('H 0 * * 1-6')]), //TODO Disabled by Mriya team request for BugFest period
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
    string(name: 'CYPRESS_BUGFEST_BRANCH', defaultValue: 'quesnelia', description: "(Required) Insert what 'stripes-testing' branch use for build"),
    folioParameters.agent(),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

CypressTestsParameters cypressParameters = new CypressTestsParameters()
cypressParameters.setCiBuildId(env.JOB_BASE_NAME)
cypressParameters.setTestsSrcBranch(params.CYPRESS_BUGFEST_BRANCH)
cypressParameters.setTenantUrl('https://bugfest-quesnelia-aqa.int.aws.folio.org')
cypressParameters.setOkapiUrl('https://okapi-bugfest-quesnelia-aqa.int.aws.folio.org')
cypressParameters.setTenant(new OkapiTenant('fs09000003')
  .withAdminUser(new OkapiUser('folio-aqa', 'Folio-aqa1')))
cypressParameters.setExecParameters('--env grepTags="smoke criticalPth extendedPath"')
cypressParameters.setTestrailProjectID('14')
cypressParameters.setTestrailRunID('2421')
cypressParameters.setWorkerLabel('cypress-static')
cypressParameters.setNumberOfWorkers(6)
cypressParameters.setTimeout('840')

boolean reportPortalUse = false
String reportPortalRunType = ''

ansiColor('xterm') {
  node(params.AGENT) {
    stage('Ini') {
      buildDescription "Branch: ${params.CYPRESS_BUGFEST_BRANCH}\nEnv: ${cypressBugfestFlowParameters.tenantUrl}"
      cleanWs()
    }

    stage('[Flow] Execute tests') {
      cypressTestsExecutionSummary = folioCypressFlow.runWrapper(cypressParameters.getCiBuildId(), reportPortalUse, reportPortalRunType) {
        folioCypressFlow.multiThreadRun(cypressParameters)
      }
    }
  }
}
