#!groovy

import org.folio.Constants
import org.folio.utilities.Tools
import org.jenkinsci.plugins.workflow.libs.Library

@Library('pipelines-shared-library@RANCHER-1983') _

properties([buildDiscarder(logRotator(numToKeepStr: '60')),
            parameters([folioParameters.cluster(),
                        folioParameters.namespace(),
                        choice(name: "ACTION", choices: ['start', 'stop', 'suspend'], description: '(Required) Choose action to perform'),
                        string(name: "AGENT", description: "Build agent", defaultValue: "rancher"),
                        folioParameters.refreshParameters()]),
            pipelineTriggers([parameterizedCron('''
        0 22 * * * %ACTION=stop
   ''')])])

ansiColor('xterm') {
  if (params.REFRESH_PARAMETERS) {
    currentBuild.result = 'ABORTED'
    println('REFRESH JOB PARAMETERS!')
    return
  }
  node("${params.AGENT}") {
    try {
      stage('Checkout') {
        checkout scm
      }
      stage('managePods') {
//        Constants.AWS_EKS_CLUSTERS.each { cluster ->
//          managePods.handlePods("${cluster}", "${params.ACTION}", "${params.NAMESPACE}")
//        }
        managePods.handlePods("${params.CLUSTER}", "${params.ACTION}", "${params.NAMESPACE}")
      }
    } catch (exception) {
      println(exception)
      error(exception.getMessage())
    }
  }
}
