#!groovy

import groovy.json.JsonSlurperClassic
import org.folio.Constants
import org.jenkinsci.plugins.workflow.libs.Library

//TODO Switch to RANCHER-741-Jenkins-Enhancements after PR review

@Library('pipelines-shared-library@RANCHER-886') _


def postgresql

properties([buildDiscarder(logRotator(numToKeepStr: '20')),
            disableConcurrentBuilds(),
            parameters([folioParameters.cluster(),
                        folioParameters.namespace(),
                        choice(name: "ACTION", choices: ['start', 'stop'], description: '(Required) Choose action to perform'),
                        choice(name: "PERIOD", choices: ['night', 'weekend'], description: '(Required) Choose period to suspend'),
                        booleanParam(defaultValue: false, description: 'Check this parameter, if you would like to suspend auto shutdown', name: 'SUSPEND'),
                        folioParameters.agent(),
                        folioParameters.refreshParameters()]),
            pipelineTriggers([parameterizedCron('''
        0 22 * * 1-5 %ACTION=stop;CLUSTER=folio-tmp;NAMESPACE=test
        15 06 * * 1-5 %ACTION=start;CLUSTER=folio-tmp;NAMESPACE=test
   ''')])])

ansiColor('xterm') {
  if (params.REFRESH_PARAMETERS) {
    currentBuild.result = 'ABORTED'
    println('REFRESH JOB PARAMETERS!')
    return
  }
  node("${params.AGENT}") {
    try {
      Calendar calendar = Calendar.getInstance()
      stage('Checkout') {
        checkout scm
      }
      if (params.SUSPEND) {
        stage("Exclude schedule apply") {
          folioHelm.withKubeConfig("${params.CLUSTER}") {
            awscli.getKubeConfig(Constants.AWS_REGION, "${params.CLUSTER}")
            kubectl.addLabelToNamespace("${params.NAMESPACE}", "shutdown-schedule", "${params.PERIOD}")
          }
        }
      } else {
        stage('[Manage environment status & state]') {
          buildName "${params.CLUSTER}-${params.NAMESPACE}.${params.ACTION}"
          buildDescription "action: ${params.ACTION}"
          switch (params.ACTION) {
            case "start":
              println("[Action ${params.ACTION} on ${params.CLUSTER}-${params.NAMESPACE}]\n[Checking...]")
              folioHelm.withK8sClient {
                awscli.getKubeConfig(Constants.AWS_REGION, "${params.CLUSTER}")
                def check = kubectl.getLabelsFromNamespace("${params.NAMESPACE}")
                def status = new JsonSlurperClassic().parseText("${check}")
                def scale_state = kubectl.getConfigMap("scale-state", "${params.NAMESPACE}", "schedule")
                def scale_state_start = new JsonSlurperClassic().parseText("${scale_state}")
                postgresql = scale_state_start.findAll { it.key.startsWith("postgresql") }
                if (status['status'] == "stopped") {
                  kubectl.addLabelToNamespace("${params.NAMESPACE}", "status", "running")
                  def services = scale_state_start.findAll { key, value -> !["mod-", "edge-", "okapi", "ldp-server", "ui-bundle"].any { prefix -> key.startsWith(prefix) } }
                  List core_modules = ["okapi", "mod-users", "mod-users-bl", "mod-login", "mod-permissions", "mod-authtoken"]
                  def core = scale_state_start.findAll { key, value -> core_modules.any { prefix -> key.startsWith(prefix) } }
                  def backend = scale_state_start.findAll { key, value -> ["mod-"].any { prefix -> key.startsWith(prefix) } }
                  def edge = scale_state_start.findAll { key, value -> ["edge-"].any { prefix -> key.startsWith(prefix) } }
                  def ui = scale_state_start.findAll { key, value -> ["ui-bundle"].any { prefix -> key.contains(prefix) } }
                  if (postgresql) {
                    postgresql.each { db ->
                      kubectl.setKubernetesResourceCount("StatefulSet", "${db.key}", "${params.NAMESPACE}", "${db.value}")
                      kubectl.waitKubernetesResourceStableState("StatefulSet", "${db.key}", "${params.NAMESPACE}", "${db.value}", '600')
                    }
                  } else {
                    awscli.startRdsCluster("rds-${params.CLUSTER}-${params.NAMESPACE}", Constants.AWS_REGION)
                    awscli.waitRdsClusterAvailable("rds-${params.CLUSTER}-${params.NAMESPACE}", Constants.AWS_REGION)
                    sleep 30
                  }
                  services.each { deployment, replica_count ->
                    kubectl.setKubernetesResourceCount('deployment', deployment.toString(), "${params.NAMESPACE}", replica_count.toString())
                    kubectl.checkDeploymentStatus("${deployment}", "${params.NAMESPACE}", "600")
                    sleep 10
                  }
                  core.each { deployment, replica_count ->
                    kubectl.setKubernetesResourceCount('deployment', deployment.toString(), "${params.NAMESPACE}", replica_count.toString())
                    kubectl.checkDeploymentStatus("${deployment}", "${params.NAMESPACE}", "600")
                    sleep 10
                  }
                  backend.each { deployment, replica_count -> kubectl.setKubernetesResourceCount('deployment', deployment.toString(), "${params.NAMESPACE}", replica_count.toString())
                  }
                  edge.each { deployment, replica_count -> kubectl.setKubernetesResourceCount('deployment', deployment.toString(), "${params.NAMESPACE}", replica_count.toString())
                  }
                  ui.each { deployment, replica_count -> kubectl.setKubernetesResourceCount('deployment', deployment.toString(), "${params.NAMESPACE}", replica_count.toString())
                  }
                  kubectl.deleteConfigMap("scale-state", "${params.NAMESPACE}")
                } else {
                  println("Target environment: ${params.CLUSTER}-${params.NAMESPACE} is already in running state!")
                  kubectl.addLabelToNamespace("${params.NAMESPACE}", "shutdown-schedule", "everyday")
                }
              }
              break
            case "stop":
              println("[Action ${params.ACTION} on ${params.CLUSTER}-${params.NAMESPACE}]\n[Checking...]")
              folioHelm.withK8sClient {
                awscli.getKubeConfig(Constants.AWS_REGION, "${params.CLUSTER}")
                def check = kubectl.getLabelsFromNamespace("${params.NAMESPACE}")
                def status = new JsonSlurperClassic().parseText("${check}")
                kubectl.createScaleState("${params.CLUSTER}", "${params.NAMESPACE}")
                def scale_state_start = new JsonSlurperClassic().parseText("${scale_state}")
                postgresql = scale_state_start.findAll { it.key.startsWith("postgresql") }
                switch (status['shutdown-schedule']) {
                  case "night":
                    if (status['status'] == "running") {
                      println("The environment: ${params.CLUSTER}-${params.NAMESPACE} has been excluded from shutdown for tonight!")
                      kubectl.addLabelToNamespace("${params.NAMESPACE}", "shutdown-schedule", "everyday")
                    }
                    break
                  case "weekend": // Saturday & Sunday included for future use.
                    if (status['status'] == "running" && calendar.get(Calendar.DAY_OF_WEEK) == 1 || 6 || 7) {
                      println("The environment: ${params.CLUSTER}-${params.NAMESPACE} has been excluded from shutdown for this weekend, skipped!")
                      kubectl.addLabelToNamespace("${params.NAMESPACE}", "shutdown-schedule", "everyday")
                    }
                    break
                  default:
                    if (postgresql) {
                      kubectl.createScaleState("${params.CLUSTER}", "${params.NAMESPACE}")
                      kubectl.addLabelToNamespace("${params.NAMESPACE}", "status", "stopped")
                      kubectl.addLabelToNamespace("${params.NAMESPACE}", "shutdown-schedule", "everyday")
                      kubectl.scaleDownResources("${params.NAMESPACE}", "Deployment")
                    } else {
                      kubectl.createScaleState("${params.CLUSTER}", "${params.NAMESPACE}")
                      kubectl.addLabelToNamespace("${params.NAMESPACE}", "status", "stopped")
                      kubectl.addLabelToNamespace("${params.NAMESPACE}", "shutdown-schedule", "everyday")
                      kubectl.scaleDownResources("${params.NAMESPACE}", "Deployment")
                      awscli.stopRdsCluster("rds-${params.CLUSTER}-${params.NAMESPACE}", Constants.AWS_REGION)
                    }
                    break
                }
              }
              break
          }
        }
      }
    } catch (exception) {
      println(exception)
      error(exception.getMessage())
    }
  }
}
