#!groovy
import hudson.util.Secret
import org.folio.jenkins.PodTemplates
import org.folio.models.parameters.KarateTestsParameters
import org.jenkinsci.plugins.workflow.libs.Library

@Library('pipelines-shared-library@RANCHER-2236') _

/**
 * Job properties and parameters
 */
properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
    folioParameters.branch('TESTS_BRANCH', 'folio-integration-tests'),
    string(name: 'TESTS', defaultValue: '', description: 'Comma separated modules list to test (no spaces).\nLeave empty to launch all.'),
    string(name: 'OKAPI_URL', defaultValue: 'https://folio-etesting-karate-kong.ci.folio.org', description: 'Target environment OKAPI URL'),
    string(name: 'KEYCLOAK_URL', defaultValue: 'https://folio-etesting-karate-keycloak.ci.folio.org', description: 'Target environment KEYCLOAK URL'),
    string(name: 'EDGE_URL', defaultValue: 'https://folio-etesting-karate-edge.ci.folio.org', description: 'Target environment EDGE URL'),
    string(name: 'SUPER_TENANT', defaultValue: 'diku', description: 'Supertenant for test tenants creation flow'),
    string(name: 'SUPER_ADMIN_USERNAME', defaultValue: 'diku_admin', description: 'Super admin username'),
    password(name: 'SUPER_ADMIN_PASSWORD', defaultValueAsSecret: Secret.fromString('admin'), description: 'Super admin user password'),
    string(name: 'PROTOTYPE_TENANT', defaultValue: 'consortium', description: 'Tenant name that will be used by tests as a prototype during test tenants creation'),
    string(name: 'THREADS_COUNT', defaultValue: '1', description: 'Number of parallel threads'),
    choice(name: 'JAVA_VERSION', choices: ['21', '17'], description: 'Java version to use for tests'),
//    booleanParam(name: 'CREATE_CUSTOM_EDGE_TENANT', defaultValue: false, description: 'Do you need to create tenant for edge modules from edge-configuration.json file?'),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

/**
 * Job variables
 */
PodTemplates podTemplates = new PodTemplates(this)

KarateTestsParameters karateTestsParams = new KarateTestsParameters()
karateTestsParams.gitBranch = params.TESTS_BRANCH
karateTestsParams.modulesToTest = params.TESTS
karateTestsParams.okapiUrl = params.OKAPI_URL
karateTestsParams.keycloakUrl = params.KEYCLOAK_URL
karateTestsParams.edgeUrl = params.EDGE_URL
karateTestsParams.tenant = params.SUPER_TENANT
karateTestsParams.adminUserName = params.SUPER_ADMIN_USERNAME
karateTestsParams.adminPassword = params.SUPER_ADMIN_PASSWORD.getPlainText()
karateTestsParams.prototypeTenant = params.PROTOTYPE_TENANT
karateTestsParams.threadsCount = params.THREADS_COUNT
karateTestsParams.javaVerson = params.JAVA_VERSION
karateTestsParams.timeout = '6'

println("Karate tests parameters: ${karateTestsParams.toString()}")

/**
 * Pipeline
 */
ansiColor('xterm') {
  podTemplates.rancherAgent {
    stage('Ini') {
      buildDescription currentBuild.getBuildCauses()[0].shortDescription
    }
  }

  folioKarateFlow.call(karateTestsParams)
}
