#!groovy

import org.folio.Constants
import org.folio.rest.model.OkapiTenant
import org.folio.utilities.model.Project
import org.jenkinsci.plugins.workflow.libs.Library

@Library('pipelines-shared-library@RANCHER-835') _

properties([
    buildDiscarder(logRotator(numToKeepStr: '30')),
    disableConcurrentBuilds(),
    parameters([
        folioParameters.clusterName(),
        folioParameters.namespace(),
        folioParameters.uiBundleBuild(),
        folioParameters.repository(),
        folioParameters.branch(),
        folioParameters.tenantId(),
        booleanParam(name: 'reBuildBundle', defaultValue: false, description: '(Optional) Rebuild UI bundle before deploy or deploy existing'),
        folioParameters.agent(),
        folioParameters.refreshParameters()
    ])
])

if (params.REFRESH_PARAMETERS) {
    currentBuild.result = 'ABORTED'
    return
}

ansiColor('xterm') {
    node(params.AGENT) {
        stage('Ini') {
            buildName ""
            buildDescription ""
        }
        /**
         * Placeholder for stages
         */
    }
}//TBD
