edge-caiasoft:
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /admin/health
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=4000
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/success-codes: 200-399
      kubernetes.io/ingress.class: alb
    hosts:
      - paths:
          - path: /caiasoftService*
            pathType: ImplementationSpecific
            servicePort: 80
  service:
    type: NodePort
  extraEnvVars: []
  integrations:
    okapi:
      enabled: true
      existingSecret: okapi-credentials
  configMaps:
    ephemeral:
      fileName: edge-caiasoft-ephemeral-properties
      existingConfig: edge-caiasoft-ephemeral-properties
  replicaCount: 1
  resources:
    limits:
      memory: 328Mi
    requests:
      memory: 286Mi
  extraJavaOpts:
    - -XX:MaxRAMPercentage=85.0