#!groovy
import org.folio.models.RancherNamespace
import org.folio.models.parameters.CreateNamespaceParameters
import org.folio.utilities.Logger

@Library('pipelines-shared-library') _

/**
 * Job properties and parameters
 */
properties([
  pipelineTriggers([cron('H 21 * * 0,2-6')]),
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
    string(name: 'CYPRESS_BRANCH', defaultValue: 'master', description: "(Required) Insert what 'stripes-testing' branch use for build"),
    folioParameters.agent(),
    folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

/**
 * Job variables
 */
Logger logger = new Logger(this, env.JOB_BASE_NAME)

final String createNamespaceJobName = '/folioRancher/folioNamespaceTools/createNamespaceFromBranch'
final String deleteNamespaceJobName = '/folioRancher/folioNamespaceTools/deleteNamespace'
final String platformCompleteBranch = 'snapshot'
String okapiVersion = folioTools.eval(folioStringScripts.getOkapiVersions(), ['FOLIO_BRANCH': platformCompleteBranch])[0]

CreateNamespaceParameters namespaceBaseParams = new CreateNamespaceParameters.Builder()
  .clusterName('folio-testing')
  .namespaceName('cypress')
  .rwSplit(false)
  .greenmail(false)
  .mockServer(false)
  .pgType('built-in')
  .pgVersion('16.1')
  .kafkaType('built-in')
  .opensearchType('aws')
  .s3Type('built-in')
  .members('')
  .worker('rancher')
  .build()

CreateNamespaceParameters namespaceFromBranchParams = namespaceBaseParams.toBuilder()
  .folioBranch(platformCompleteBranch)
  .okapiVersion(okapiVersion)
  .configType('testing')
  .loadReference(true)
  .loadSample(true)
  .consortia(true)
  .rtr(false)
  .build()

RancherNamespace namespace = new RancherNamespace(namespaceBaseParams.getClusterName(), namespaceBaseParams.getNamespaceName())

Map cypressFlowParameters = [
  customBuildName       : env.JOB_BASE_NAME,
  branch                : params.CYPRESS_BRANCH,
  tenantUrl             : "https://${namespace.generateDomain('diku')}",
  okapiUrl              : "https://${namespace.getDomains().okapi}",
  tenantId              : 'diku',
  adminUsername         : 'diku_admin',
  adminPassword         : 'admin',
  parallelExecParameters: '--env grepTags="smoke criticalPath"',
//  sequentialExecParameters: '--env grepTags="smoke+nonParallel criticalPath+nonParallel"',
  testsTimeout          : '8',
  testrailProjectID     : '14',
  testrailRunID         : '2108',
  numberOfWorkers       : '12',
  agent                 : 'cypress',
  runType               : 'night',
  useReportPortal       : 'true'
]

/**
 * Pipeline
 */
ansiColor('xterm') {
  node(params.AGENT) {
    try {
      stage('Ini') {
        buildDescription "Branch: ${params.CYPRESS_BRANCH}\nEnv: ${cypressFlowParameters.tenantUrl}"
        cleanWs()
      }

      stage('[Job] Destroy environment') {
        def nsExists
        folioHelm.withKubeConfig(namespaceBaseParams.getClusterName()) {
          nsExists = kubectl.checkNamespaceExistence("${namespaceBaseParams.getNamespaceName()}")
        }
        if (nsExists) {
          retry(2) {
            folioTriggerJob.deleteNamespace(deleteNamespaceJobName, namespaceBaseParams)
          }
        } else {
          logger.warning("${namespaceBaseParams.getNamespaceName()} namespace does not exists!")
        }
      }

      stage('[Job] Provision environment') {
        try {
          folioTriggerJob.createNamespaceFromBranch(createNamespaceJobName, namespaceFromBranchParams)
        } catch (Exception new_ex) {
          slackSend(attachments: folioSlackNotificationUtils.renderFailedBuildResultMessage()
            , channel: "#rancher_tests_notifications")
          throw new Exception("Provision of the environment is failed: " + new_ex)
        }
      }

      stage('[Flow] Execute tests') {
        folioCypressFlow(cypressFlowParameters)
      }
    } catch (e) {
      logger.warning("Caught exception: ${e}")
      error(e.getMessage())
    } finally {
      stage('Cleanup') {
        logger.debug("Workspace size: ${sh(returnStdout: true, script: 'du -sh .').trim()}")
        cleanWs notFailBuild: true
      }
    }
  }
}
