#!groovy

@Library('pipelines-shared-library@RANCHER-650-Jenkins-upgrade') _

import org.folio.models.RancherNamespace
import org.folio.rest_v2.Main
import org.jenkinsci.plugins.workflow.libs.Library
import org.folio.jenkins.JenkinsAgentLabel
import org.folio.jenkins.PodTemplates

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
    folioParameters.cluster(),
    folioParameters.namespace(),
    folioParameters.refreshParameters()])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  error('DRY RUN BUILD, PARAMETERS REFRESHED!')
}

RancherNamespace namespace = new RancherNamespace(params.CLUSTER, params.NAMESPACE)
  .withSuperTenantAdminUser()

Main main = new Main(this, namespace.getDomains()['okapi'], namespace.getSuperTenant())
namespace.setSuperTenantLocked(main.isTenantLocked(namespace.getSuperTenant()))

ansiColor('xterm') {
  PodTemplates podTemplates = new PodTemplates(this)

  podTemplates.defaultTemplate {
    node(JenkinsAgentLabel.DEFAULT_AGENT.getLabel()) {
      try {
        stage('Ini') {
          buildName "${namespace.getClusterName()}-${namespace.getNamespaceName()}.${env.BUILD_ID}"
        }
        stage("Lock Supertenant") {
          if (!namespace.getSuperTenantLocked()) {
            main.lockSuperTenant(namespace.getSuperTenant())
            println("SuperTenant was successfully locked!")
          } else {
            println("SuperTenant already locked!")
          }
        }
      } catch (exception) {
        println(exception)
        error(exception.getMessage())
      }
    }
  }
}
