#!groovy

@Library('pipelines-shared-library@RANCHER-741-Jenkins-Enhancements') _

import org.folio.models.OkapiTenant
import org.folio.models.RancherNamespace
import org.folio.rest_v2.Main
import org.jenkinsci.plugins.workflow.libs.Library
import org.folio.models.InstallRequestParams

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
    folioParameters.cluster(),
    folioParameters.namespace(),
    folioParameters.tenantId(''),
    folioParameters.agent(),
    folioParameters.refreshParameters()])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  error('DRY RUN BUILD, PARAMETERS REFRESHED!')
}

RancherNamespace namespace = new RancherNamespace(params.CLUSTER, params.NAMESPACE)
  .withSuperTenantAdminUser()

Main main = new Main(this, namespace.getDomains()['okapi'], namespace.getSuperTenant())

if (!main.isTenantExist(params.TENANT_ID)) {
  currentBuild.result = 'ABORTED'
  error('Tenant does not exist, stopping the pipeline')
}

InstallRequestParams installRequestParams = new InstallRequestParams()
    .withTenantParameters("purge=true")

OkapiTenant tenant = new OkapiTenant(params.TENANT_ID)
  .withInstallJson(main.getInstallJson(params.TENANT_ID, 'disable'))
  .withInstallRequestParams(installRequestParams)


ansiColor('xterm') {
  node(params.AGENT) {
    try {
      stage('Ini') {
        buildName "${namespace.getClusterName()}-${namespace.getNamespaceName()}.${env.BUILD_ID}"
        buildDescription "Tenant: ${params.TENANT_ID}"
      }
      stage("Disable tenant modules") {
        main.tenantInstall(tenant, tenant.getModules().getInstallJson())
        println("modules removed")
      }
      stage("Delete tenant") {
        main.deleteTenant(tenant)
      }
    } catch (exception) {
      println(exception)
      error(exception.getMessage())
    } finally {
      stage('Cleanup') {
        cleanWs notFailBuild: true
      }
    }
  }
}
