#!groovy
package folioRancher.folioNamespaceTools.manageNamespace.createNamespace

import groovy.transform.Field
import org.folio.models.parameters.CreateNamespaceParameters
import org.folio.Constants
import org.jenkinsci.plugins.workflow.libs.Library

@Library('pipelines-shared-library@RANCHER-2936-test') _

@Field final String createNamespaceJobName = Constants.JENKINS_CREATE_NAMESPACE_FROM_BRANCH_JOB

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  parameters([
    folioParameters.cluster(),
    folioParameters.namespace(),
    folioParameters.platformFromCluster(),
    folioParameters.platformBranch(),
    folioParameters.branch(),
    booleanParam(name: 'CONSORTIA', defaultValue: true, description: '(Optional) Set true to create consortium'),
    folioParameters.refreshParameters()
    , folioParameters.hideParameters(['PLATFORM'])
    , folioParameters.hideParameters(
    [
      'EUREKA': ['FOLIO_BRANCH'],
      'OKAPI' : ['PLATFORM_BRANCH']
    ]
    , 'PLATFORM')
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

//if (params.CLUSTER != 'folio-tmp') {
//  folioCommon.validateNamespace(params.NAMESPACE)
//}

CreateNamespaceParameters namespace = new CreateNamespaceParameters.Builder()
  .clusterName(params.CLUSTER)
  .namespaceName(params.NAMESPACE)
  .platformBranch(params.PLATFORM_BRANCH)
  .folioBranch(params.FOLIO_BRANCH)
  .consortia(params.CONSORTIA)
  .build(this)

ansiColor('xterm') {
  podTemplates.rancherAgent {
    stage('Checkout') {
      checkout scm
    }

    stage('Build name') {
      buildName "${namespace.getClusterName()}-${namespace.getNamespaceName()}.${env.BUILD_ID}"
      buildDescription "Branch: ${namespace.platformBranch}\nConfig: ${params.CONFIG_TYPE}"
    }

    stage('Spinning up env') {
      folioTriggerJob.createNamespaceFromBranch(createNamespaceJobName, namespace)
    }
  }
}
