---
mod-data-import:
  extraEnvVars:
    - name: SPLIT_FILES_ENABLED
      value: 'true'
    - name: DI_INITIALIZATION_STARTED_PARTITIONS
      value: '8'
    - name: DI_RAW_RECORDS_CHUNK_READ_PARTITIONS
      value: '8'
    - name: ASYNC_PROCESSOR_MAX_WORKERS_COUNT
      value: '8'
  integrations:
    s3:
      enabled: true
      existingSecret: s3-mod-data-import-credentials
