#!groovy
import org.folio.jenkins.JenkinsAgentLabel
import org.folio.jenkins.PodTemplates
import org.folio.models.OkapiTenant
import org.folio.rest_v2.Configurations
import org.folio.rest_v2.Constants

@Library('pipelines-shared-library@RANCHER-650-Jenkins-upgrade') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
    folioParameters.cluster(),
    folioParameters.namespace(),
    booleanParam(name: 'ResetPasswordLink', defaultValue: false, description: 'ResetPasswordLink for tenant'),
    string(name: 'TENANT_ID', defaultValue: '', description: 'Tenant ID'),
    folioParameters.refreshParameters()
  ])
])

OkapiTenant tenant = folioDefault.tenants()[params.TENANT_ID as String]
tenant.okapiConfig.withResetPasswordLink("https://${params.CLUSTER}-${params.NAMESPACE}-${params.TENANT_ID}.${Constants.CI_ROOT_DOMAIN}")
Configurations config = new Configurations(this, "${params.CLUSTER}-${params.NAMESPACE}-okapi.${Constants.CI_ROOT_DOMAIN}")


if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

if (params.CLUSTER == 'folio-testing') {
  folioCommon.kitfoxApproval()
}

PodTemplates podTemplates = new PodTemplates(this)

ansiColor('xterm') {
  podTemplates.defaultTemplate {
    node(JenkinsAgentLabel.DEFAULT_AGENT.getLabel()) {
      stage('Ini') {
        buildName "${params.CLUSTER}-${params.NAMESPACE}.${env.BUILD_ID}"
        buildDescription "CONFIGURE: ${params.TENANT_ID}"
      }
      stage('Checkout') {
        checkout scm
      }

      stage('Configure tenant') {
        if (params.ResetPasswordLink) {
          config.setResetPasswordLink(tenant)
        }

        /**
         * The rest configuration activities placeholder: Reindex, SMTP, etc.
         */
      }
    }
  }
}
