#!groovy

import org.jenkinsci.plugins.workflow.libs.Library
import org.folio.Constants

@Library('pipelines-shared-library@RANCHER-839') _

properties([
  //pipelineTriggers([cron('H 0 * * *')]),  # need to implement cron time
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}
Map Parameters = [
  FOLIO_REPOSITORY                  : 'platform-complete',
  FOLIO_BRANCH_SRC                  : 'R1-2024',
  FOLIO_BRANCH_DST                  : 'snapshot',
  BACKUP_NAME                       : 'opbf-bugfest-snapshot-04-12-2023',
]

ansiColor('xterm') {
  node(params.AGENT) {
    stage('Ini') {
      buildName env.BUILD_ID
      buildDescription ""
      cleanWs()
    }

    stage('[Job] Execute Schema Comparison Job') {
      script {
        try {
          build job: Constants.JENKINS_JOB_SCHEMA_COMPARE,
            parameters:
              [string(name: 'FOLIO_REPOSITORY', value: FOLIO_REPOSITORY),
               string(name: 'FOLIO_BRANCH_SRC', value: FOLIO_BRANCH_SRC),
               string(name: 'FOLIO_BRANCH_DST', value: FOLIO_BRANCH_DST),
               string(name: 'BACKUP_NAME', value: BACKUP_NAME),]
        } catch (Exception new_ex) {
          slackNotifications.sendPipelineFailSlackNotification("#folioschemacompare")
          throw new Exception("Execution Of Schema Comparison Job Failed: " + new_ex.getMessage())
        }
      }
    }
  }
}
