#!groovy
import org.folio.Constants
import org.folio.jenkins.PodTemplates

@Library('pipelines-shared-library') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
    string(name: 'DOCKERFILE_BRANCH', defaultValue: 'master', description: 'Dockerfile Branch'),
    string(name: 'JAVA_VERSION', defaultValue: '21', description: 'Java base image version'),
    string(name: 'IMAGE_TAG', defaultValue: "21-alpine-jdk", description: 'Image Tag'),
    folioParameters.refreshParameters()
  ])
])

// Early exit if refresh parameters is triggered
if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

PodTemplates podTemplates = new PodTemplates(this)
def dockerfilePath = './scripts/docker/jenkins/javaContainer'

ansiColor('xterm') {
  podTemplates.werfAgent {
    stage('[Git] Checkout source') {
      checkout scmGit(
        branches: [[name: "*/${env.DOCKERFILE_BRANCH}"]],
        extensions: [],
        userRemoteConfigs: [[url: 'https://github.com/folio-org/pipelines-shared-library.git']]
      )
    }

    stage('[Docker] Build and push') {
      common.checkEcrRepoExistence('amazoncorretto')
      dir(dockerfilePath) {
        container('werf') {
          withAWS(credentials: Constants.ECR_FOLIO_REPOSITORY_CREDENTIALS_ID, region: Constants.AWS_REGION) {
            withCredentials([usernamePassword(credentialsId: Constants.DOCKER_FOLIOCI_PULL_CREDENTIALS_ID,
              usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
              String ecrLoginString = ecrLogin()
              String dockerHubLoginString = "werf cr login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} https://index.docker.io/v1/"
              sh """
                set -eu +x
                ${ecrLoginString.replace('docker', 'werf cr')}
                ${dockerHubLoginString}
                set -x
                export JAVA_VERSION=${env.JAVA_VERSION.trim()}
                werf build --repo ${Constants.ECR_FOLIO_REPOSITORY}/werf-shadow \
                  --loose-giterminism

                werf export --repo ${Constants.ECR_FOLIO_REPOSITORY}/werf-shadow \
                  --tag ${Constants.ECR_FOLIO_REPOSITORY}/amazoncorretto:${env.IMAGE_TAG} \
                  --loose-giterminism
              """.stripIndent()
            }
          }
        }
      }
    }
  }
}
