#!groovy

import org.folio.jenkins.PodTemplates
import org.folio.utilities.Logger
import org.jenkinsci.plugins.workflow.libs.Library

@Library('pipelines-shared-library@db_dump_restore') _

properties([
  buildDiscarder(logRotator(numToKeepStr: '30')),
  disableConcurrentBuilds(),
  parameters([
    folioParameters.cluster(),
    folioParameters.namespace(),
    stashFile 'SCHEMA_DUMP',
      folioParameters.refreshParameters()
  ])
])

if (params.REFRESH_PARAMETERS) {
  currentBuild.result = 'ABORTED'
  return
}

if (params.CLUSTER == 'folio-etesting') {
  folioCommon.kitfoxApproval()
}

PodTemplates podTemplates = new PodTemplates(this)
Logger logger = new Logger(this, env.JOB_BASE_NAME)

ansiColor('xterm') {
  podTemplates.rancherAgent {
    try {
      stage('Ini') {
        buildName('Restore schema dump: ' + params.SCHEMA_DUMP)
        buildDescription('Target environment: ' + params.CLUSTER + '-' + params.NAMESPACE)
      }
      stage('Checkout') {
        checkout scm
      }
      stage('[isRunning]') {
        folioHelm.withKubeConfig(params.CLUSTER) {
          def check = sh(script: "kubectl get pods --namespace ${params.NAMESPACE} --no-headers", returnStdout: true).trim()
          if (!check.contains(module.getName())) {
            logger.error("Reason: target env is not running or module: ${module.getName()} is not presented in environment")
          }
        }
      }
      stage('Prepare') {
        logger.info("Preparing to restore schema dump: ${params.SCHEMA_DUMP} to environment: ${params.CLUSTER}-${params.NAMESPACE}")
        unstash 'SCHEMA_DUMP'
        sh "du -sh $SCHEMA_DUMP_FILE"
      }
    } catch (e) {
      logger.warning("Caught exception: ${e}")
      error(e.getMessage())
    }
  }
}
